CREATE TABLE IF NOT EXISTS tokens (
    id VARCHAR PRIMARY KEY UNIQUE NOT NULL,
    value VARCHAR,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    expires_at TIMESTAMPTZ NOT NULL
);