CREATE TABLE IF NOT EXISTS tokens (
    id VARCHAR PRIMARY KEY UNIQUE NOT NULL,
    user_id VARCHAR,
    target VARCHAR NOT NULL,
    value VARCHAR NOT NULL,
    reason VARCHAR NOT NULL,
    type VARCHAR NOT NULL,
    is_used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    expires_at TIMESTAMPTZ NOT NULL
);